blank_issues_enabled: false
contact_links:
  - name: Rocket League Map Making discord server
    url: https://discord.gg/PWu3ZWa
    about: Visit our Discord server to ask questions about map making 
  - name: UDK setup
    url: https://github.com/RocketLeagueMapmaking/UDK_RL_Setup/issues
    about: Visit the UDK setup repo for issue related to the setup script
  - name: Theme
    url: https://github.com/RocketLeagueMapmaking/theme-rlmm/issues
    about: Visit the website theme repo for issues with the design of the website
