name: Deploy
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version of the website to deploy'
        required: true
        default: '1.0.0'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Updating the website (version ${{ github.event.inputs.version }})!"
      - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: sh deployment/update_and_deploy.sh ${{ github.event.inputs.version }}