name: Deploy
  on:
    workflow_dispatch:
      inputs:
        version:
          description: 'The version of the website to deploy'
          required: true
          default: '1.0.0'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Updating the website (version ${{ github.event.inputs.version }})!"
# TODO: login, update container and give result