name: Preview fork deploys
# Maybe use more events at some point?
on: 
  push:
    branches-ignore:
      - "main"
      - "master"
  pull_request_target: 
    types:
      - "opened"
jobs:
  preview:
    runs-on: ubuntu-latest
    # Only add forks that have the secrets configured
    if: github.repository_owner == 'ghostrider-05'
    permissions:
      contents: read
      deployments: write
    name: Publish preview to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install node.js v14
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build Vuepress
        run: npm run docs:build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.CLOUDFLARE_PROJECTNAME }}
          directory: /docs/.vuepress/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}