name: Preview fork deploys
on: 
  push:
    branches-ignore:
      - "main"
      - "master"
  pull_request_target: 
    types:
      - "opened"
jobs:
  preview:
    runs-on: ubuntu-latest
    if: ${{ secrets.CLOUDFLARE_API_TOKEN && github.repository_owner != 'RocketLeagueMapmaking' }}
    permissions:
      contents: read
      deployments: write
    name: Publish preview to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Vuepress
        run: npm run docs:build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.CLOUDFLARE_PROJECTNAME }}
          directory: /docs/.vuepress/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}