name: Test
on: [push, pull_request]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install node.js v18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run eslint
        run: npm run lint

      - name: Run markdown lint
        run: npm run lint-markdown

      - name: Run file lint
        run: npm run lint-files

        # Broken links are checked by VitePress on building
        # Make sure that ignoreDeadlinks is enabled!
        # https://vitepress.dev/reference/site-config#ignoredeadlinks
      - name: Check guide build
        run: npm run docs:build
        env:
            BUILD_NOTIFICATION_URL: ${{ secrets.BUILD_NOTIFICATION_URL }}