name: Test
on: [push, pull_request]
jobs:
  lint:
    name: Lint & test v${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Run for both the node version used and the next major version
        node: [18, 20]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install node.js v${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run eslint
        run: npm run lint

      - name: Run markdown lint
        run: npm run lint-markdown

      - name: Run file lint
        run: npm run lint-files

        # Broken links are checked by VitePress on building
        # Make sure that ignoreDeadlinks is enabled!
        # https://vitepress.dev/reference/site-config#ignoredeadlinks
      - name: Check guide build
        run: npm run docs:build
        env:
            BUILD_NOTIFICATION_URL: ${{ secrets.BUILD_NOTIFICATION_URL }}